### ISSUE TITLE
build example file

### ISSUE THREAD

**Issue by flyash07** [libcsp/libcsp#399]
I'm not able to build the example file properly to make the csp_server_client executable. I've tried building the example directory multiple times but i the executable is not generated. Please help T_T

**Comment by yashi** [comment]
Care to share how you built? Please show us the entire commands you entered as well as the output.

**Comment by flyash07** [comment]
Okay so here's what I've done so far
- I changed python to python3 in the buildall.py file 
- used cmake and ninja to build as given in the install.md file
```
cmake -GNinja -B builddir
cd builddir
ninja
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to MinSizeRel
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'libzmq'
-- Checking for one of the modules 'libsocketcan'
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/srishti/penguin/csp/libcsp-develop/builddir
[40/40] Linking C shared library liblibcsp.so
```
in the examples directory i gave-
```
cmake ..
```
got this output:
```
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to MinSizeRel
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'libzmq'
-- Checking for one of the modules 'libsocketcan'
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/srishti/penguin/csp/libcsp-develop/examples
```
I gave this command in the terminal:
`./buildall.py` in the examples directory
and i got this output:
```
Traceback (most recent call last):
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 70, in <module>
    main(args.build_system, rest)
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 56, in main
    build_with_waf()
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 50, in build_with_waf
    subprocess.check_call(['./waf', 'distclean', 'configure', 'build'])
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './waf'
```
Now i had no idea why it was using waf so i changed `DEFAULT_BUILD_SYSTEM = 'waf'` to `DEFAULT_BUILD_SYSTEM = 'cmake'` and gave `./buildall.py` again
Now i got this:
```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.2s)
CMake Warning (dev) at CMakeLists.txt:4 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "csp_server_client" links to:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:14 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "zmqproxy" links to:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done (0.0s)
-- Build files have been written to: /home/srishti/penguin/csp/libcsp-develop/examples/build
ninja: Entering directory `build'
ninja: error: unknown target 'examples/csp_server_client'
Traceback (most recent call last):
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 70, in <module>
    main(args.build_system, rest)
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 58, in main
    build_with_cmake()
  File "/home/srishti/penguin/csp/libcsp-develop/examples/./buildall.py", line 32, in build_with_cmake
    subprocess.check_call(cmake_compile + targets)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'build', 'examples/csp_server_client', 'examples/csp_arch', 'examples/zmqproxy']' returned non-zero exit status 1.
```

Now i have no clue what to do further :(

**Comment by yashi** [comment]
### Using buildall.py
If you are happy using `buildall.py`, all you need to do is to run it.

```
$ examples/buildall.py
'distclean' finished successfully (0.000s)
Setting top to                           : /home/yashi/src/libcsp 
Setting out to                           : /home/yashi/src/libcsp/build 
Checking for 'gcc' (C compiler)          : /usr/lib/ccache/gcc 
Checking for program 'python'            : /usr/bin/python 
Checking for header stdio.h              : yes 
Checking for header sys/socket.h         : yes 
Checking for header arpa/inet.h          : yes 
'configure' finished successfully (0.078s)
Waf: Entering directory `/home/yashi/src/libcsp/build'
[ 1/37] Compiling src/interfaces/csp_if_can.c
[ 2/37] Compiling src/csp_hex_dump.c
[ 3/37] Compiling src/crypto/csp_hmac.c
[ 4/37] Compiling src/arch/posix/csp_semaphore.c
[ 5/37] Compiling src/arch/posix/csp_clock.c
[ 6/37] Compiling src/csp_init.c
[ 7/37] Compiling src/crypto/csp_sha1.c
[ 8/37] Compiling src/interfaces/csp_if_kiss.c
[ 9/37] Compiling src/csp_id.c
[10/37] Compiling src/csp_sfp.c
[11/37] Compiling src/interfaces/csp_if_can_pbuf.c
[12/37] Compiling src/csp_dedup.c
[13/37] Compiling src/csp_service_handler.c
[14/37] Compiling src/arch/posix/pthread_queue.c
[15/37] Compiling src/csp_rtable_cidr.c
[16/37] Compiling src/csp_crc32.c
[17/37] Compiling src/csp_rdp_queue.c
[18/37] Compiling src/arch/posix/csp_queue.c
[19/37] Compiling src/csp_qfifo.c
[20/37] Compiling src/csp_buffer.c
[21/37] Compiling src/csp_port.c
[22/37] Compiling src/arch/posix/csp_system.c
[23/37] Compiling src/interfaces/csp_if_udp.c
[24/37] Compiling src/csp_iflist.c
[25/37] Compiling src/csp_services.c
[26/37] Compiling src/interfaces/csp_if_i2c.c
[27/37] Compiling src/csp_debug.c
[28/37] Compiling src/csp_route.c
[29/37] Compiling src/arch/posix/csp_time.c
[30/37] Compiling src/csp_promisc.c
[31/37] Compiling src/csp_bridge.c
[32/37] Compiling src/csp_rtable_stdio.c
[33/37] Compiling src/interfaces/csp_if_lo.c
[34/37] Compiling src/csp_conn.c
[35/37] Compiling src/csp_rdp.c
[36/37] Compiling src/csp_io.c
[37/37] Linking build/libcsp.a
Waf: Leaving directory `/home/yashi/src/libcsp/build'
'build' finished successfully (0.086s)
'distclean' finished successfully (0.002s)
Setting top to                           : /home/yashi/src/libcsp 
Setting out to                           : /home/yashi/src/libcsp/build 
Checking for 'gcc' (C compiler)          : /usr/lib/ccache/gcc 
Checking for program 'python'            : /usr/bin/python 
Checking for header stdio.h              : yes 
Checking for header sys/socket.h         : yes 
Checking for header arpa/inet.h          : yes 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'libsocketcan'              : yes 
Checking for 'libzmq'                    : yes 
'configure' finished successfully (0.083s)
Waf: Entering directory `/home/yashi/src/libcsp/build'
[ 1/48] Compiling src/drivers/can/can_socketcan.c
[ 2/48] Compiling src/csp_hex_dump.c
[ 3/48] Compiling src/crypto/csp_hmac.c
[ 4/48] Compiling src/arch/posix/csp_semaphore.c
[ 5/48] Compiling src/arch/posix/csp_clock.c
[ 6/48] Compiling src/csp_sfp.c
[ 7/48] Compiling src/csp_services.c
[ 8/48] Compiling src/csp_dedup.c
[ 9/48] Compiling src/csp_service_handler.c
[10/48] Compiling src/csp_port.c
[11/48] Compiling src/arch/posix/csp_system.c
[12/48] Compiling src/interfaces/csp_if_lo.c
[13/48] Compiling src/csp_init.c
[14/48] Compiling src/interfaces/csp_if_i2c.c
[15/48] Compiling src/crypto/csp_sha1.c
[16/48] Compiling src/interfaces/csp_if_can.c
[17/48] Compiling src/csp_id.c
[18/48] Compiling src/drivers/usart/usart_kiss.c
[19/48] Compiling src/csp_rtable_stdio.c
[20/48] Compiling src/csp_debug.c
[21/48] Compiling src/arch/posix/pthread_queue.c
[22/48] Compiling src/csp_rtable_cidr.c
[23/48] Compiling src/csp_route.c
[24/48] Compiling src/csp_rdp_queue.c
[25/48] Compiling src/csp_crc32.c
[26/48] Compiling src/arch/posix/csp_queue.c
[27/48] Compiling src/csp_qfifo.c
[28/48] Compiling src/csp_buffer.c
[29/48] Compiling src/interfaces/csp_if_zmqhub.c
[30/48] Compiling src/csp_bridge.c
[31/48] Compiling src/interfaces/csp_if_kiss.c
[32/48] Compiling src/csp_iflist.c
[33/48] Compiling src/drivers/usart/usart_linux.c
[34/48] Compiling src/csp_rdp.c
[35/48] Compiling src/csp_conn.c
[36/48] Compiling src/arch/posix/csp_time.c
[37/48] Compiling src/csp_promisc.c
[38/48] Compiling src/interfaces/csp_if_udp.c
[39/48] Compiling src/interfaces/csp_if_can_pbuf.c
[40/48] Compiling src/csp_io.c
[41/48] Compiling examples/csp_server_client_posix.c
[42/48] Compiling examples/csp_server_client.c
[43/48] Compiling examples/csp_arch.c
[44/48] Compiling examples/zmqproxy.c
[45/48] Linking build/libcsp.a
[46/48] Linking build/examples/csp_server_client
[47/48] Linking build/examples/csp_arch
[48/48] Linking build/examples/zmqproxy
Waf: Leaving directory `/home/yashi/src/libcsp/build'
'build' finished successfully (0.260s)
```

This will build `libcsp.a` as well as all examples using `waf`.

```
$ ls build/libcsp.a build/examples/*(*)
build/examples/csp_arch  build/examples/csp_server_client  build/examples/zmqproxy  build/libcsp.a
```

If you want to use CMake, give `--build-system cmake`

```
$ examples/buildall.py --build-system cmake
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to MinSizeRel
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for one of the modules 'libzmq'
-- Checking for one of the modules 'libsocketcan'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yashi/src/libcsp/build
ninja: Entering directory `build'
[49/49] Linking C executable examples/zmqproxy

$ ls build/liblibcsp.so build/examples/*(*)
build/examples/csp_arch  build/examples/csp_server_client  build/examples/zmqproxy  build/liblibcsp.so
```

The file name is a bit mess (I should have fixed it for long time), but it should build fine.

### Using Plain CMake

If you want to build it without `buildall.py` but `cmake` by yourself, do

```
$ cmake -S . -B builddir
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to MinSizeRel
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for one of the modules 'libzmq'
-- Checking for one of the modules 'libsocketcan'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yashi/src/libcsp/builddir

$ cd builddir
$ ninja
[42/42] Linking C shared library liblibcsp.so

$ ninja -t targets
edit_cache: phony
rebuild_cache: phony
src/edit_cache: phony
src/rebuild_cache: phony
src/arch/edit_cache: phony
src/arch/rebuild_cache: phony
src/arch/posix/edit_cache: phony
src/arch/posix/rebuild_cache: phony
src/crypto/edit_cache: phony
src/crypto/rebuild_cache: phony
src/drivers/edit_cache: phony
src/drivers/rebuild_cache: phony
src/interfaces/edit_cache: phony
src/interfaces/rebuild_cache: phony
examples/edit_cache: phony
examples/rebuild_cache: phony
csp_arch: phony
csp_server_client: phony
driver_can: phony
if_zmq: phony
libcsp: phony
zmqproxy: phony
all: phony
build.ninja: RERUN_CMAKE
clean: CLEAN
help: HELP

$ ninja csp_server_client
[3/3] Linking C executable examples/csp_server_client

$ ls examples
CMakeFiles  cmake_install.cmake  csp_server_client
```

**Comment by yashi** [comment]
BTW, there is a package called `python-is-python3`.

```
sudo apt install python-is-python3
```

Might saves you a second.

**Comment by flyash07** [comment]
I installed the zmq library and python-is-python3 and the below command worked for me:
cmake -GNinja -S . -B builddir
Thank you so much
But now the problem I'm facing is after I give the ./csp_server_client in the directory where its present, without any options, the cursor just blinks and nothing happens. Is it supposed to take a long time or something?
EDIT: I had to copy paste the include folder inside examples directory and i gave this command at the top of the CMakeLists.txt files in the libcsp-develop and examples directory:
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)

**Comment by yashi** [comment]
Ah, thanks.  That's because `CSP_PRINT_STDIO` is not set with CMake. Moreover, you have to manually change `0` to `1` in `CMakeLists.txt` with the current `develop` branch.

The variable should be in the cache so that we can [set it with `-D`](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry).

```
cmake -S . -B builddir -DCSP_PRINT_STDIO=1 
```

The following change should be applied.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2c89c44..ef0cb54 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,7 +18,7 @@ endif()
 
 set(CSP_HAVE_STDIO 1)
 set(CSP_ENABLE_CSP_PRINT 1)
-set(CSP_PRINT_STDIO 0)
+set(CSP_PRINT_STDIO 0 CACHE BOOL "Use C standard I/O for csp_print")
 set(CSP_QFIFO_LEN 15 CACHE STRING "Length of incoming queue for router task.")
 set(CSP_PORT_MAX_BIND 16 CACHE STRING "Length of incoming queue for router task")
 set(CSP_CONN_RXQUEUE_LEN 16 CACHE STRING "Number of packets in connection queue")
```

And also for PC the value should be `1` for the default.

**Comment by flyash07** [comment]
Okay thank you so much that worked. Thanks for all the help.
