### ISSUE TITLE
buildall.py: Unable to build without ZMQ

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#413]
Without libzmq3-dev installed on my Debian system, you can't build libcsp with `buildall.py`

**waf** (configuration time error)
```
Checking for 'libzmq'                    : not found 
The configuration failed
(complete log in /home/yashi/src/libcsp/build/config.log)
Traceback (most recent call last):
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 71, in <module>
    main(args.build_system, rest)
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 57, in main
    build_with_waf()
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 52, in build_with_waf
    subprocess.check_call(['./waf', 'distclean', 'configure', 'build'] + options)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./waf', 'distclean', 'configure', 'build', '--with-os=posix', '--enable-rdp', '--enable-promisc', '--enable-crc32', '--enable-hmac', '--enable-dedup', '--enable-python3-bindings', '--enable-can-socketcan', '--with-driver-usart=linux', '--enable-if-zmqhub', '--enable-examples']' returned non-zero exit status 1.
```

**cmake** (build time error)
```
[43/48] Building C object examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o
FAILED: examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o 
/usr/lib/ccache/cc  -I/home/yashi/src/libcsp/include -I/home/yashi/src/libcsp/build -Os -DNDEBUG -MD -MT examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o -MF examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o.d -o examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o -c /home/yashi/src/libcsp/examples/zmqproxy.c
/home/yashi/src/libcsp/examples/zmqproxy.c:3:10: fatal error: zmq.h: No such file or directory
    3 | #include <zmq.h>
      |          ^~~~~~~
compilation terminated.
[44/48] Building C object CMakeFiles/csp.dir/src/csp_service_handler.c.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 71, in <module>
    main(args.build_system, rest)
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 59, in main
    build_with_cmake()
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 32, in build_with_cmake
    subprocess.check_call(cmake_compile + targets)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'build', 'examples/csp_server_client', 'examples/csp_arch', 'examples/zmqproxy']' returned non-zero exit status 1.
```

**meson** (build time error)
```
Run-time dependency libzmq found: NO (tried pkgconfig and cmake)
Has header "sys/socket.h" : YES 
Has header "arpa/inet.h" : YES 
Configuring csp_autoconfig.h using configuration
Build targets in project: 4

Found ninja-1.11.1 at /usr/bin/ninja
ninja: Entering directory `build'
[41/50] Compiling C object examples/zmqproxy.p/zmqproxy.c.o
FAILED: examples/zmqproxy.p/zmqproxy.c.o 
sccache cc -Iexamples/zmqproxy.p -Iexamples -I../examples -I. -I.. -I../include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=gnu11 -Os -g -pthread -Wshadow -Wcast-align -Wwrite-strings -Wno-unused-parameter -MD -MQ examples/zmqproxy.p/zmqproxy.c.o -MF examples/zmqproxy.p/zmqproxy.c.o.d -o examples/zmqproxy.p/zmqproxy.c.o -c ../examples/zmqproxy.c
../examples/zmqproxy.c:3:10: fatal error: zmq.h: No such file or directory
    3 | #include <zmq.h>
      |          ^~~~~~~
compilation terminated.
[45/50] Compiling C object libcsp.so.p/src_csp_service_handler.c.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 71, in <module>
    main(args.build_system, rest)
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 61, in main
    build_with_meson()
  File "/home/yashi/src/libcsp/./examples/buildall.py", line 20, in build_with_meson
    subprocess.check_call(meson_compile + targets)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'build', 'examples/csp_server_client', 'examples/csp_arch', 'examples/zmqproxy']' returned non-zero exit status 1.
```

**Comment by yashi** [comment]
On second thought, `example/buildall.py` explicitly specifies `--enable-if-zmqhub`, which requires zmq. So the behavior is correct.

I'm closing this.
