### ISSUE TITLE
buildall.py fails in container

### ISSUE THREAD

**Issue by danieldavidson** [libcsp/libcsp#451]
I'm running on an Intel Mac, so I'm exploring libcsp in an Ubuntu container. I've tried to replicate the containers that are used in the Build and Test workflow. That is, using both `gcc` or `clang` with a `cmake` build. In both cases the build fails when linking `zmqproxy`. Using https://github.com/libcsp/libcsp/issues/399 as a reference, I was able to successfully build and run the example. The installed packages are the same, but build steps are different than what's executed in `buildall.py`. I'd appreciate some guidance on why `buildall.py` is not working in my container environment, and why the manual execution of steps seems to overcome the issue.

GCC container
```
FROM ubuntu:22.04

RUN apt-get update && apt-get -y install \
    build-essential \
    cmake \
    git \
    libsocketcan-dev \
    libzmq3-dev \
    ninja-build \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/libcsp/libcsp.git
WORKDIR /libcsp
RUN python3 ./examples/buildall.py --build-system=cmake
```

Clang container
```
FROM ubuntu:22.04

ENV CC=/usr/lib/llvm-15/bin/clang CXX=/usr/lib/llvm-15/bin/clang++

RUN apt-get update && apt-get -y install \
    build-essential \
    clang-15 \
    cmake \
    git \
    libsocketcan-dev \
    libzmq3-dev \
    ninja-build \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/libcsp/libcsp.git
WORKDIR /libcsp
RUN python3 ./examples/buildall.py --build-system=cmake
```

Error log
```
</snip>
[47/47] Linking C executable examples/zmqproxy
FAILED: examples/zmqproxy 
: && /usr/bin/cc -Os -DNDEBUG  examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o -o examples/zmqproxy  -Wl,-rpath,/libcsp/build  libcsp.so && :
/usr/bin/ld: examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o: in function `task_capture':
zmqproxy.c:(.text+0x3f): undefined reference to `zmq_socket'
/usr/bin/ld: zmqproxy.c:(.text+0x51): undefined reference to `zmq_connect'
/usr/bin/ld: zmqproxy.c:(.text+0x67): undefined reference to `zmq_setsockopt'
/usr/bin/ld: zmqproxy.c:(.text+0xcf): undefined reference to `zmq_msg_data'
/usr/bin/ld: zmqproxy.c:(.text+0x163): undefined reference to `zmq_msg_close'
/usr/bin/ld: zmqproxy.c:(.text+0x175): undefined reference to `zmq_msg_init_size'
/usr/bin/ld: zmqproxy.c:(.text+0x182): undefined reference to `zmq_msg_recv'
/usr/bin/ld: zmqproxy.c:(.text+0x18e): undefined reference to `zmq_msg_close'
/usr/bin/ld: zmqproxy.c:(.text+0x193): undefined reference to `zmq_errno'
/usr/bin/ld: zmqproxy.c:(.text+0x19a): undefined reference to `zmq_strerror'
/usr/bin/ld: zmqproxy.c:(.text+0x1b2): undefined reference to `zmq_msg_size'
/usr/bin/ld: zmqproxy.c:(.text+0x1de): undefined reference to `zmq_msg_recv'
/usr/bin/ld: zmqproxy.c:(.text+0x1ea): undefined reference to `zmq_msg_close'
/usr/bin/ld: examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o: in function `main':
zmqproxy.c:(.text.startup+0xcd): undefined reference to `zmq_ctx_new'
/usr/bin/ld: zmqproxy.c:(.text.startup+0xdd): undefined reference to `zmq_socket'
/usr/bin/ld: zmqproxy.c:(.text.startup+0xef): undefined reference to `zmq_bind'
/usr/bin/ld: zmqproxy.c:(.text.startup+0x111): undefined reference to `zmq_socket'
/usr/bin/ld: zmqproxy.c:(.text.startup+0x123): undefined reference to `zmq_bind'
/usr/bin/ld: zmqproxy.c:(.text.startup+0x159): undefined reference to `zmq_proxy'
/usr/bin/ld: zmqproxy.c:(.text.startup+0x16f): undefined reference to `zmq_ctx_destroy'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/libcsp/examples/buildall.py", line 71, in <module>
    main(args.build_system, rest)
  File "/libcsp/examples/buildall.py", line 59, in main
    build_with_cmake()
  File "/libcsp/examples/buildall.py", line 32, in build_with_cmake
    subprocess.check_call(cmake_compile + targets)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'build', 'examples/csp_server_client', 'examples/csp_arch', 'examples/zmqproxy']' returned non-zero exit status 1.
```

Working container config
```
FROM ubuntu:22.04

RUN apt-get update && apt-get -y install \
    build-essential \
    cmake \
    git \
    libsocketcan-dev \
    libzmq3-dev \
    ninja-build \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/libcsp/libcsp.git
WORKDIR /libcsp
RUN cmake -GNinja -B build
RUN ninja -C build
RUN ninja -C build -t targets
RUN ninja -C build csp_server_client
```

**Comment by yashi** [comment]
Hi, this is a known issue. I'd be better if CMake fails for configuration.
Please refer to #413.  Thanks.

**Comment by danieldavidson** [comment]
Is `apt-get install`-ing `libzmq3-dev` not enough to overcome the issue mentioned in #413? All three Dockerfiles include `libzmq3-dev`.

**Comment by danieldavidson** [comment]
I realized that the Dockerfile that is successful, works because I'm only linking the `csp_server_client` target. `csp_server_client` is only the first of three targets in `buildall.py`, but it's enough to run the example. Linking `zmqproxy` fails with the same errors about undefined references that I pasted above.

**Comment by yashi** [comment]
> Is `apt-get install`-ing `libzmq3-dev` not enough to overcome the issue mentioned in #413? All three Dockerfiles include `libzmq3-dev`.

Oops.  You are right.

Do you have `pkg-config` installed?

The line:

```
: && /usr/bin/cc -Os -DNDEBUG  examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o -o examples/zmqproxy  -Wl,-rpath,/libcsp/build  libcsp.so && :
```

should be like:

```
: && /usr/bin/cc -Os -DNDEBUG  examples/CMakeFiles/zmqproxy.dir/zmqproxy.c.o -o examples/zmqproxy  -Wl,-rpath,/home/yashi/src/libcsp/build  libcsp.so  -lzmq && :
```

Because you don't have `-lzmq` part, it fails.
</details>

**Comment by danieldavidson** [comment]
That solved it. I appreciate your help! 🙏
